In [ ]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [ ]:
import numpy as np


arr1 = np.array([1,2,3,4])
arr2 = np.zeros([2,3])
arr3 = np.ones([4,5])
arr4 = np.arange(20)
arr5 = np.linspace(0,10,3)

print(arr1)
print(arr2)
print(arr3)
print(arr4)
print(arr5)


[1 2 3 4]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 0.  5. 10.]


In [ ]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

print(np.sqrt(arr1))
print(np.sin(arr1))

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1.         1.41421356 1.73205081]
[0.84147098 0.90929743 0.14112001]


In [ ]:
arr = np.array([1,2,3,4,5,6])
print(arr.shape)
print(arr.ndim)

arr = arr.reshape(2,3)
print(arr)

(6,)
1
[[1 2 3]
 [4 5 6]]


In [ ]:
arr=np.array([1,2,3,4,5])
print(arr[0])
print(arr[1:3])
mask=arr>3
print(arr[mask])

1
[2 3]
[4 5]


In [ ]:
arr=np.array([1,2,3,4,5])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))


arr1=np.array([[1,2],[3,4]])
arr2=np.array([[5,6],[7,8]])
print(np.dot(arr1,arr2))


3.0
3.0
1.4142135623730951
[[19 22]
 [43 50]]


In [ ]:
arr=np.random.rand(5)
print(arr)

np.random.seed(0)
arr=np.random.rand(5)
print(arr)

[0.56769835 0.85060154 0.7018104  0.97098921 0.86042135]
[0.5488135  0.71518937 0.60276338 0.54488318 0.4236548 ]


In [ ]:
arr1=np.array([1,2,3])
arr2=np.array([4])

print(arr1+arr2)

[5 6 7]
